// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image5":
            case "Probe":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . b . . . . . 
. . . . . . . e e . b . b . . . 
. . . . . . . . c c c b . . . . 
. . . . c c . f f f f b b b . . 
. . . . c c . f 2 2 f . . . . . 
. . . . c c c f 2 2 f . . . . . 
. . . e c c c f f f f e . . . . 
. . . e . . c c . . . e . . . . 
. . . . . . . e e . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image7":
            case "ProbeS":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . b . . . . . 
. . . . . . . e e . b . b . . . 
. . . . . . . . c c c b . . . . 
. . . . c c . f f f f b b b . . 
. . . . c c . f 2 2 f . . . . . 
. . . . c c c f 2 2 f . . . . . 
. . . e c c c f f f f e . . . . 
. . . e . . c c . . . e . . . . 
. . . . . . . e e . . . . . . . 
. . . . . . . 2 . . . . . . . . 
. . . . . . . 2 . . . . . . . . 
. . . . . . 2 2 2 2 . . . . . . 
. . . . . . . . . 2 . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "ProbeN":return img`
. . . . . . 2 . 2 . . . . . . . 
. . . . . . . 2 2 . . . . . . . 
. . . . . . . 2 . . b . . . . . 
. . . . . . . e e . b . b . . . 
. . . . . . . . c c c b . . . . 
. . . . c c . f f f f b b b . . 
. . . . c c . f 2 2 f . . . . . 
. . . . c c c f 2 2 f . . . . . 
. . . e c c c f f f f e . . . . 
. . . e . . c c . . . e . . . . 
. . . . . . . e e . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image9":
            case "myImage3":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . b . . . . . 
. . . . . . . e e . b . b . . . 
. . . . . . . . c c c b . . . . 
. . . . c c . f f f f b b b . . 
. . . . c c . f 2 2 f . . . . . 
. . . . c c c f 2 2 f . . . . . 
. 2 2 e c c c f f f f e . . . . 
2 2 . e . . c c . . . e . . . . 
2 2 . . . . . e e . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image8":
            case "ProbeE":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . b . . . . . 
. . . . . . . e e . b . b . . . 
. . . . . . . . c c c b . . . . 
. . . . c c . f f f f b b b . . 
. . . . c c . f 2 2 f . . . . . 
. . . . c c c f 2 2 f . . 2 2 2 
. . . e c c c f f f f e . 2 . . 
. . . e . . c c . . . e 2 2 2 2 
. . . . . . . e e . . . . . 2 . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image10":
            case "LBL":return img`
. . . . . 
. . . . . 
. . . . . 
. . . . . 
. . . . . 
`;
            case "image1":
            case "quad":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bbbbbb1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffbffffffffffffffffbffbfffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffffffffffffbfffbbfffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffbfffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffbbbffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffbbfbfffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffbbfffbbbfffffffffffffffffffbffffffbffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffbfffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffbfffffffffffffffffffffffffff1fbffbfffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffff1bfffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffbffffffffffffffffffffff1ffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffbfbfffffffffffffffffffffffffbbbbbbfffffffffffffffffffffffffb1fffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffbffbfffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffbfffbffffffffffffff1fffffffbffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffbffffbfffffffffffffffffbbfffbffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffbfffff1ffffffffffffffffffbbbfffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffbffffffbffffffffffffffffffff1fffffffffffffffffffff1ffbffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffbffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff1fffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffbffffffffb1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffbfffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffbffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffbfffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffbfbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff1bbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffbb1ffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbffffffffffffffffffffffffffffffffffffffffffff1bbffffbfffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffbffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffffffffffffffffffffffffffffffffffffffffffffbfffffffbfffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffbffffffffffffffffffffffffffffffffffffffffffffbfffffffbfffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffbfffffffbffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffffffffffffffffffffffffffffffffffffffbffffffffbffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffffffffffffffffffffff1fbffffffffbffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbffffffffffffffffffffffffffffffffffffffffbfffffffffffbffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffbffffffffffffffffffffffffffffffffffffffffbfffffffffffbffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbfffffffffffffffffffffffffffffffffffffffffbfffffffffffbffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbfffffffffffffffffffffffffffffffffffffffffbffffffffffbfffffffffff
ffffffffffffffff1ffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffbffffffffffbfffffffffff
ffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffbffffffffffbfffffffffff
ffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffbfffffffffffbfffffffffff
fffffffffff1ffffbfffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbfffffffffff
ffffffffffffbfffbffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbfffffffffff
ffffffffffffbfffbfffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff1ffffffffffffffffffffffffbffffffffffbffffffffffff
fffffffffffffbffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bffffbfffffffffffffffffffffffbffffffffffbffffffffffff
fffffffffffffbffbfffffffffffffffffffffffffbbbbbb1ffffffffffffffffffffffffffffffffffffffffffffffffffffffb1fffffffbfffffffffffffffffffffffbffffffffffbffffffffffff
fffffffffffffbffbffffffff1bbbff1bfbbbbbbbbfffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffffffffffffffffffff1bfbbbbffffbffffffffffff
fffffffffffffffffffffffbbffffbbbbffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffff1fbffffffffbffffffffffffffffffffbbbfffffffbbbfbffffffffffff
ffffffffffffffffffffffbfffffffffbffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffff1fbbbffffffffffffbbbffffffffffffffbffffffffffff
fffffffffffffffff1fffbffffffffffbffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffbbbbffffffbbffffffffffffffffbfffffffffffff
fffffffffffffffff1ffffffffffffffbffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbbb1fffffffffffffffffffff1ffffffffffff
ffffffffffffffffffbffffffffffffbfffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbbfffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffbffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffbfffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffbfffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffbffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffbffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfbfffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffbfffffffffbffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffbfffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffbfffffbffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffbffffff1ffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffbfffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffbfffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffbfffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1bbfffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffbb1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffbbbffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffff1fffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffff1bbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffb1bfffffffffffffff1bfffffffffffffffffffffffffffffbfffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffffffffffbbfbbbbfffffffffffffffffffffffbbffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffbbfffffffbbfffffffffffffffffffbbffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bfffffffffffff1fffffffffffffff1ffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffbfffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbffffffffffffffffffffbb1fffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffbfffffffffffffffffbbbbffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbf1fffffffffffff1fbbbffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffbbf1fffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffb1bbfffbfffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffbbffffffffffbffffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbfffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffb1bbbfff1ffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffff1ffffbbfffffbbbbfffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffbffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffb1ffffffffffffffffffffffffffffffffffff1bffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbb1bbffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbb1ffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image2":
            case "quad0":return img`
bbffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbb1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffbffffffffffffffffffffffffffffffffffffffffffffffffffbfffffff1fbfffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffff1bbbbbbb1ffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffb1bbbbb1fffffffffffffffffffffffffffffffffffffffffffffffffffff1bffffffffffffffffff
fff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fbffffffffbbbfffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffffffffffffffffff
ffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbfffffffffffffffff
ffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffbfffffffffffffffff
ffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffbffffffffffffffff
ffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbffffffffffffffff
ffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbfffffffffffffff
ffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffbffffffffffffff
ffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbffffffffffffff
ffffbfffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbfffffffffffff
ffffbfffffffff1fffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffb1ffffffffffff
ffffb1ffffffffbbffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbfffffffffffff
ffffffbfffffffbbfffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbffffffffffffff
ffffffbfffffffbffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbfffffffffffffff
fffffffbfffffbfffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbffffffffffffffff
fffffffbfffffbf1ffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffffffffffff
fffffffbfffffbfbfffffffff1fbbbbbbfffffffbbffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbffffffffffffffffff
ffffffffbffffbffbffffffffffffffffbbbbb1bfffffffffffffffffffffffffffffff111ffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffbfffbfffffffffffffffffff
ffffffffbfffbffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffff1bfbffffffffffffffffffff
ffffffffffffbfffffbbffffffffffffffffffffbfffffffffffffffffffffffffffffffffbffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffff
fffffffffffbbfffffffbfffffffffffffffffffbfffffffff1fffffffffffffffffffffffbfffffffffbfbb1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffff1fffffffffbffffffffffffffffffbffffffffffffffffffffffffffffffffffbffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffbffffffffffffffffffbfffffffffffffffffffffffffffffffffbfffffffbffbfffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffff
fffffffffffffffffffffffbfffffffffffffffffbffffffffffffffffffffffffffffffffffbffffbbbffbffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffff
ffffffffffffffffffffffffbfffffffffffffffffbfffffffffffffffffffffffffffffffffbbbbbffffffbffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffff
fffffffffffffffffffffffffbffffffffffffffffbffffffffffffffffffffffffffffffbbbf1ffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffff
ffffffffffffffffffffffffffbbffffffffffffffbffffffffffffffffffffffffffff1fffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffffff
ffffffffffffffffffffffffffffbffffffffffffffbfffffffffffffffffffffffffffffffffffbfffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffff
fffffffffffffffffffffffffffffbfffffffffffffbfffffffffffffffffffffffffffffffffffbffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffff
ffffffffffffffffffffffffffffffbfffffffffffff1ffffffffffffffffffffffffffffffffffbfffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffff
fffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffff
fffffffffffffffffffffffffffffff1ff1fffffffffffffffffffffffffffffffffffffffffffffffbfffffffffff1bbfffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffbffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffbfffbbfffffffffffffffffffffffffffffffffffffffffffffffffffbffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bbfffffffbfffffbbffffffffffffffffffffffffffffff1fffffffffffffffffffbfffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfbffffffbfffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbfffffbfffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffb1fffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbfffff1ffffffffffffffffffffffffffffffffffffffffffffbbbbbbbfffffbbfffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffbb1bbfffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffff1fff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff1ffbffffffffffffffff11fffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffff11bbb1fffffffffffffffffffffffffffffffffffffffffffff1ffffbfffffffffffffffffffffffffffffbff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffbffffffffffffffffffffffffffffffbf
ffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffbfffffffffffffffffffffffffffffffb
fffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbfffffffffffffffffffffffffbbbbbb1
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbffffffff1bbbff1bfbbbbbbbbfffffbf
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffbbbbffffffffffffffbf
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffbffffffffffffffbf
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffbffffffffffbffffffffffffffbf
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffbffffffffffffffbf
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffbfffffffffffffffbf
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbb1bffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbfffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffbffffffffffffffff1f
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffbfffffffff1fffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffbffffbffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fff11fffffffffffff1fbbbbbffffffffffffffffffffffffffffffffffffffffffffbffffbffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff111f11ffffffffffffffffffffffbbbb1fffffffffffffffffffffffffffffffffbfffffbffffbffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffbbbbb1fbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff1ffffbffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbffffffbbbbfffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffff1fff1fffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffb1fffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbf1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbb1ffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bbbffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1bffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1b
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbf1fffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1bbfffbfffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffbfffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1bbbfff1fff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffbbfffffbbbbfff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1fffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image3":
            case "quad1":return img`
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffbfffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1fffffffffffffffffffffb1bffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffb1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbbffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbbbffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffbbffffffffffffffffffffffffffffffffffffffffffbbb1ffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbfffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbbbbbbbbfffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbbbbb1fffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff1ffffffffffffffffffffffffffffffffffffffffbfffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffbfffffffffffffffffffffffffffffffffffffffff1bbbbbfffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffbbbbbf1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffff
fffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffff
fffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffff
ffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbb1fbbfffffffffffffffffffffffffff
ffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffbbbbffbfffbbbffffffffffffffffffffffff
ffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbf1bbffffffbffffffbbbfffffffffffffffffffff
fffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffbfffffffbfffffffffb1fffffffb1ffffffffff
fffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbffffffffffffffbfffffffbfffffffffffbbfffbbffffffffffff
fffffffffbffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffb1fbbbffffffffffbfffffbffffffffffffffbbbffffffffffffff
ffffffffbfffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbffffff1fffffffffbfffffbfffffffffffffffffffffffffffffff
ffffffffbffffffffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffbffffffffffffbffffffffbbfffffffbfffffbfffffffffffffffffffffffffffffff
ffffffffbffffffffffffffffffffffffffffffffffffbfffbffffffffffffffffffffffffffffffffffffffffbfffffffffffff1ffffffffff1fffffffbffffbfffffffffffffffffffffffffffffff
fffffffbffffffffffffffffffffffffffffffffffffbfffffbbffffffffffffffffffffffffffffffffffffffbffffffffffffffbfffffffffffffffffbfff1ffffffffffffffffffffffffffffffff
fffffffbffffffffffffffffffffffffffffffffffffbfffffffbfffffffffffffffffffffffffffffffffffffbfffffffffffffffbfffffffffffffffff1bb1ffffffffffffffffffffffffffffffff
ffffffbffffffffffffffffffffffffffffffffffffbfffffffffbbfffffffffffffffffffffffffffffffffffbffffffffffffffffbffffffffffffffffbfffbfffffffffffffffffffffffffffffff
ffffffbfffffffffffffffffffffffffffffffff1ffbfffffffffff1fffffffffffffffffffffffffff1ffffbbbffffffffffffffff1ffffffffffffffffbfffbfffffffffffffffffffffffffffffff
ffffffbfffffffffffffffffffffffffffffffbffbbbfffffffffffbffffffffffffffffffffffffffff11fbfffbbb1bbbbbbb1fffffffffffffffffffff1ffffbffffffffffffffffffffffffffffff
fffffbfffffffffffffffffffffffffffffffbffffb1ffffffffffbfffffffffffffffffffffffffffffffbfbfffffffffffffffbffffffffffffffffffffffffbffffffffffffffffffffffffffffff
fffffbfffffffffffffffffffffffffffffffbfffffffffffffffbffffffffffffffffffffffffffffffffb1fbffffffffffffffbffffffffffffffffffffbbbb1ffffffffffffffffffffffffffffff
fffffbffffffffffffffffffffffffffffffbfffffffffffffffbffffffffffffffffffffffffffffffffbffffbbfffffffffffffbfffffffffffffffffff1ffffbbbfffffffffffffffffffffffffff
ffffbfffffffffffffffffffffffffffffffbffffffffffffffbffffffffffffffffffffffffffffffffbfffffffbfffffffffffffbfffffffffffffffffbffffffffbb1ffffffffffffffffffffffff
ffffbffffffffffffffffffffffffffffffbffffffffffffffbfffffffffffffffffffffffffffffffffbffffffffbffffffffffffbfffffffffffffffffbfffffffffbfffffffffffffffffffffffff
ffffbffffffffffffffffffffffffffffffbfffffffffffffbfffffffffffffffffffffffffffffffff1ffffffffffbffffffffffff1fffffffffffffffbffffffffffbfffffffffffffffff1fffffff
fffbffffffffffffffffffffffffffffffbffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffffffffffffffffbffffffffffbffffffffffffffffbbfffffff
fffbfffffffffffffffffffffffffffffbffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffbbfffffffbfffffffffffffffffbffffffffffbfffffffffffffffbfbfffffff
fffbfffffffffffffffffffffffffffffbfffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffbffffbbffffffffffff1bfffbfffffffffffbfffffffffffff1bffbfffffff
fffbffffffffffffffffffffffffffffbfffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffbffbffffffffffffffffbbfbffffffffffffffffffffffffffbffbfffffff
fffbfffffffffffffffffffffffff11fbffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffb1fffffffffffffffffff1ffffffffffffffffffffffffffffbfbfffffff
fffbfffffffffffffffffffffffff1ffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfbffffff
fffbffffffffffffffffffffffffffbffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1ffffff
ffbfffffffffffffffffffffffffffbfffffffffff1fffffffffffffffffffffffff1bbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffbfffffffffffffffffffffffffffbfffffffffffbffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffbfffffffffffffffffffffffffffbfffffffffffbffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffbfffffffffffffffffffffffffffbfffffffffffbffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffff
ffbfffffffffffffffffffffffffffbfffffffffffbffffffffffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffbffffff
ffbfffffffffffffffffffffffffffbfffffffffffbffffffffffffffffffffffffffffffffffffb1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffbfffff
ffbfffffffffffffffffffffffffffbffffffffffbffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffbffffffffffffbffff
fbffffffffffffffffffffffffffffbffffffffffbffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffbffffffffffffbffff
fbffffffff1ffffffffffffffffffffbfffffffffbfffffffffffffffffffffffffffffffffffffbfffffffffffffffff1ffffffffffffffffffffffffffffffffffffffbffffffbffffffffffffbfff
fbffffffffffbfffffffffffffffffffbffffffffbfffffffffffffffffffffffffffffffffffffbffffffffffffffffffbffffffffffffffffffffffffffffffffffffbffffffffbfffffffffffbfff
fbfffffffffffbffffffffffffffffffbffffffffbffffffffffffffffffffffffffffffffffffbfffffffffffffffffffbffffffffffffffffffffffffffffffffffbbffffffffff1ffffffffffbfff
fbffffffffbfffbfffffffffffffffffbffffffffbffffffffffffffffffffffffffffffffffffbffffffffffffffffffffbffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffff
fbfffffffbfffffbbfffffffffffffffbfffffffbfffffffffffffffffffffffffffffffffffffbffffffffffffffffffffbfffffffffffffffffffffffffffffffbfffffffffffffffbffffffffffff
b1fffffffbfffffffbffffffffffffffbfffffffbffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffbffffffffffffffffffffffffffffff1fffffffffffffffffbbffffff1fff
fffffffffbffffffff1fffffffffffffbfffffffbffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffbffffffffffffffffffffffffffffbffffffffffffffffffff1ffffffbff
fffffffffbfffffffbffffffffffffffbfffffffbfffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffbffffffffffffffffffffffffffffbfffffffffffffffffffffffffffbff
fffffffffbfffffffbffffffffffffffbfffffffbfffffffffffffffffffffffffffffffffffbffffffffffffffffffffffff1fffffffffffffffffffffffffffbffffffffffffffffffffbffffffbff
fbfffffffbfffffffbffffffffffffffbffffff1fffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffbffffffffffffffffffffffffffffbffffffffffffffffffffbffffffbff
fbfffffffbfffffffbffffffffffffffbfffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffbffffffffffffffffffffbffffffbff
fbfffffffbfffffffbfffffffffffffff1bbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffbffffffffffffffffffffbffffffbff
ffbffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffb1ffffffffffffffffffffbffffffbff
ffbfffffffffffff1fffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffbfffffffffffffffffffffbfffffffff
ffbffff1fbbbbbffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffbfffffffff
fffbffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffbfffffbb1f
fffbfffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffbfffffffffffffffffffffff1bbbbffff
fffbfffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffbfffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffbfffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb1ffffffffffffffffffffffffffbffffffffffbfbbb1fffffffffffffffff
ffffbfffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffbffffffffffbfffbffffffffffffffffff
ffffbffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffbffffffffffbfffbffffffffffffffffff
fffffbfffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbfffbffffffffffffffffff
fffffbfffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bbfbfffffffffffffffffffffffffffff1ffffffffffbfffbffffffffffffffffff
fffffbfffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffff1bffbfffffffffffffffff
ffffffbffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffffff
ffffffbffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffff
ffffffbfffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffff
fffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbffbfffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffbb1bffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image4":
            case "quad2":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff1bfbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbffbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffbffbffffffbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffbbfffbffffffffffbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffbbbbbb1fffffffffffffffffffffffffffffffffffffffffffffffffffffb1ffbbbbffffffffffffffbb1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffffffb1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffbbbffffffffffffffbffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbbffffffffffffbfffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffbbbffffffffbffffb1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbbfffffbfbbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffbbf11bbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffbbb1fffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffb1fffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffbbfffffffffffffffffffffffffffffffffffffffffffffffffffbbbbfffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfbbffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffff1ffbbbbffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffbffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffbffffffffffffffffffffffffffff
ffffffffffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffffffffbfffffffffffffffffffffffffff
fffffffffffbbbbbbbfffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbfffffffffffffffffffffffffff
fffffffbbbbfffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffbffffffffffffffffffffffffff
fffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffbffffffffffffffffffffffffff
ffff1fffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffffffffffffffffffffffffff
fffffbfffffffffffffffffffffbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbfffffffffffffffffffffffff
ffffffbfffffffffffffffffffffffffbbbbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffffbfffffffffffffffffffffffff
fffffffbbffffffffffffffffffffffffffffffbbbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbffffffffffffffffffffffff
fffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffbffffffffffffffffffffffff
ffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbffffffffffffffffffffffff
fffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffff1bfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffbfffffffffffffffffffffff
ffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffff
ffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffff1ffffffffffffffffffffff
fffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffbfbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffff
ffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffbfffbffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffbfffbffffffffffffffffffffff
fffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffbffffbfffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffbfffbffffffffffffffffffffff
fffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffbffffbffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffbffffffffffffffffffffff
ffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffbfffffbfffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbfbffffffffffffffffffffff
fffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffffffbffffffbbfffffffffffffffffff1fffffffffffffffffffffffffbffffffffffffbbffffffffffffffffffffff
fffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffbfffffffbfffffffffffffffffffffffffffffffffffffffffffffbffffffffffffb1fffffffffffffffffffff
ffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffbffffffffbffffffffffffffffffbfffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffbfffffffffbfffffffffffffffffbfffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffffffbffffffffffbffffffffffffffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffbffffffffffbbffffffffffffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffbffffffffffffbfffffffffffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffbfffffffffffffbfffffffffffffbfffffffffffffffffffffffffbffffffffffffffffffffffffffffffffff
bffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffbfffffffffffff1ffffffffffffbffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffff
fbfffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffbffffffffffffbbffffffffffffbffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffff
ffbbffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffbffffffffffbbffffffffffffffbffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffff
ffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffbbffffffffffffffffbfffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffff
fffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffbbfffffffffffffffffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffffbbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffb11fbbfffffffffffffffffffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffffffbfffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffff111bfffffffffffffffffffffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
fffffffffbffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffffffffbbffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffffffffffbffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
fffffffffffffbfffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffbffffffffffffffffffffffffffffffff
ffffffffffffffbbfffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffbbbbbb1ffffffffffffbffffffffffffffffffffffffffffffff
ffffffffffffffffbffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bbfbbbbbfffffffffffffffffffbffffffffffffffffffffffffffffffff
fffffffffffffffffbffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffbfffffffffffbfffffffffff1ffffffffffffffffffff
fffffffffffffffff1bfffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1bbfffbffffffffffffffbbffffffffffbffffffffffffbffffffffffffffffff
fffffffffffffffffffbbbffffffffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffbffffffffffffffffbbffffffffbffffffffffffbffffffffffffffffff
ffffffffffffffffffffffbbbfffbbffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffbfffffffbffffffffffffffffff1fffffffbffffffffffbfbffffffffffffffffff
fffffffffffffffffffffffffbb1fffffffffffffffffffffffffffffffffbbfffffffffffffffffffffffffffffbffffffffbffffffffffffffffffffffffffbffffffffffbfbffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfbb1ffffffffffffffffffffffffffbffffffffbffffffffffffffffffffffffffbffffffffffbffbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffbfffffffffffffffffffffffffbfffffffffbffffffffffffffffffffffffffbffffffffffbffbfffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffbffffffffffffffffffffffffbffffffffffbffffffffffffffffffffffffffbffffffffffbffbfffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffbffffbffffffffffffffffffffffffffffffffffffbf1fffffffffffffffffffffffbffffffffffbfffbffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fff1fffbfffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffbffffffffffbfffbffffffffffffffff
fbb1fbbffffffffffffffffffffffffffffffffffffffffffffffffff1fffbffbfffffffffffffffffffffffffffffffffffff11ffffffffffffffffffffffffbffffffffffbfffbffffffffffffffff
fffbfffbbbffffffffffffffffffffffffffffffffffffffffffffff1fffffb1ffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffff11ffffffffbfffbffffffffffffffff
fffbffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffbffffffffbffffbfffffffffffffff
fffbfffffffffb1fffffffb1fffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbffffbfffffffffffffff
fffbfffffffffffbbfffbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbffffbfffffffffffffff
ffbffffffffffffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffff1ffffffffffffff
ffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffbffffffffffffff
ffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffbffffffffffffff
ffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffbffffffffffffff
f1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbfffffbffffffffffffff
f1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbffffffbfffffffffffff
ffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffbffffffbfffffffffffff
ffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffbfffffffbfffffffffffff
fffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffbfffffffffffff
fffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffffffbffffffffffff
fbb1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbfffffbffffffffffff
ffffbbbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbfffffbffffffffffff
fffffffbb1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffbfffffbffffffffffff
ffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffffff1fffffffffff
ffffffffbfffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffbffffffffffffffffff
ffffffffbffffffffffffffffbbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffff1ffffbffffffffffff
ffffffffbfffffffffffffffbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffbbfffffffffffff
ffffffffbfffffffffffff1bffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffff1bfffffffffffffff
fffffffffffffffffffffffbffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffff
ffffffffffffffffffffffffbfbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffff
ffffffffffffffffffffffffbbfbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffff
ffffffffffffffffffffffffffb1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffff
fffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffff
fffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffff
fffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffffffffffff
fffffffffffffff1fffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbffffffffffffffffffff
ffffffffffffffbbffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbfffffffffffffffff
ffffffffffffbbffbffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbfffffffffffffff
fffffffffffbffffbffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffff
ffffffffffbffffffbffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffbffffffffbfffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffbbffffffffff1ffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
